version: '3.8'

services:
  db:
    image: postgres:17
    container_name: bus_tracker_db
    environment:
      POSTGRES_USER: bususer
      POSTGRES_PASSWORD: bus
      POSTGRES_DB: bus_tracker
      TZ: Europe/Zagreb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bususer -d bus_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: vozi_brate_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: Europe/Zagreb
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bus_tracker
      SPRING_DATASOURCE_USERNAME: bususer
      SPRING_DATASOURCE_PASSWORD: bus
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_APPLICATION_NAME: bus-tracker

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      TZ: Europe/Zagreb
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
